repositories:
  - prefix: bitnami
    urls:
      - https://charts.bitnami.com/bitnami
  - prefix: jetstack
    urls:
      - https://charts.jetstack.io
  - prefix: jenkins-x
    urls:
      - https://storage.googleapis.com/chartmuseum.jenkins-x.io
      - http://chartmuseum.jenkins-x.io
  - prefix: jx-labs
    urls:
      - https://storage.googleapis.com/jenkinsxio-labs/charts
  - prefix: stable
    urls:
      - https://charts.helm.sh/stable
  - prefix: flagger
    urls:
      - https://flagger.app
  - prefix: gloo
    urls:
      - https://storage.googleapis.com/solo-public-helm
  - prefix: external-secrets
    urls:
      - https://external-secrets.github.io/kubernetes-external-secrets
  - prefix: incubator
    urls:
      - https://kubernetes-charts-incubator.storage.googleapis.com
  - prefix: eks
    urls:
      - https://aws.github.io/eks-charts
  - prefix: ingress-nginx
    urls:
      - https://kubernetes.github.io/ingress-nginx
